services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    networks:
      - private
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - private

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - private
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 5

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    depends_on:
      ollama:
        condition: service_healthy
    command: ["pull", "${OLLAMA_MODEL}"]
    networks:
      - private

  ollama-embed-init:
    image: ollama/ollama:latest
    container_name: ollama-embed-init
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL}
    depends_on:
      ollama:
        condition: service_healthy
    command: ["pull", "${OLLAMA_EMBED_MODEL}"]
    networks:
      - private

  ingest:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: ingest
    depends_on:
      chroma:
        condition: service_started
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
      ollama-embed-init:
        condition: service_completed_successfully
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
    command: ["python", "-c", "from app.src.services.ingest_service import ingest_documents; ingest_documents()"]
    networks:
      - private


  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: api
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
      ollama-embed-init:
        condition: service_completed_successfully
      ingest:
        condition: service_completed_successfully
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8080:8080"
    networks:
      - private
      - public

networks:
  private:
    driver: bridge
  public:
    driver: bridge

volumes:
  ollama_data:
  chroma_data: